CC=gcc

all:linear_search binary_search

linear_search:linear_search.c
	$(CC) linear_search.c -o linear_search

binary_search:binary_search.c
	$(CC) binary_search.c -o binary_search

.PHONY:
clean:
	rm linear_search binary_search
