CC=gcc

all: count_odd.o plus_onc.o search_insert_position.o two_sum.o

count_odd.o: count_odd.c
	$(CC) count_odd.c -o count_odd

plus_onc.o: plus_onc.c
	$(CC) plus_onc.c -o plus_one

search_insert_position.o: search_insert_position.c
	$(CC) search_insert_position.c -o  search_insert_position

two_sum.o: two_sum.c
	$(CC) two_sum.c -o two_sum
