CC=gcc

all: count_odd plus_onc search_insert_position two_sum

count_odd: count_odd.c
	$(CC) count_odd.c -o count_odd

plus_onc: plus_onc.c
	$(CC) plus_onc.c -o plus_one

search_insert_position: search_insert_position.c
	$(CC) search_insert_position.c -o  search_insert_position

two_sum: two_sum.c
	$(CC) two_sum.c -o two_sum

.PHONY:
clean:
	rm two_sum search_insert_position plus_one count_odd
